version: '3.8'

services:
  nodejsapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
      - elasticsearch

    networks:
      - app_network

  mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Manage
      - MONGO_INITDB_ROOT_USERNAME=jilee
      - MONGO_INITDB_ROOT_PASSWORD=jilee
    restart: unless-stopped
    networks:
      - app_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - app_network

volumes:
  mongodb_data:
  elasticsearch_data:


networks:
  app_network:
    driver: bridge
